version: "3.9"
services:
  deep-research:
    platform: linux/arm64
    image: justincnn/deep-research:latest
    container_name: deep-research
    env_file:
      - .env
    ports:
      - "2278:3000"
